# Generated by Django 4.2.5 on 2023-10-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_remove_product_cart_quantity_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
