# Generated by Django 4.2.5 on 2023-10-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_product_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
